### ISSUE TITLE
request

### ISSUE THREAD

**Issue by jenyjos** [narenkram/steadfast-monorepo#1]
sir, kindly add shoonya by finvasia also to this. it could help many of us. thanks

**Comment by narenkram** [comment]
@jenyjos Will add it in a few days.

**Comment by jenyjos** [comment]
thanks

**Comment by jenyjos** [comment]
sir, the kill switch may hit accidently . so can you add a confirmation with **yes or no** for that.

**Comment by narenkram** [comment]
@jenyjos sure.

**Comment by jenyjos** [comment]
How to session was very helpful. could run for Dhan. waiting for shoonya integration. i have a question, currently i have only dhan so how can I make it my default choice. whenever I am opening flattrade is coming as default.
![Screenshot 2024-07-04 182408](https://github.com/narenkram/steadfast-stoic-monorepo/assets/155707434/3e4ba807-090c-412f-8011-ac54ce0fe1aa)

**Comment by narenkram** [comment]
@jenyjos ability to set a default broker has been added, pull updates.

**Comment by krinacool** [comment]
Hello, I am waiting for shoonya integration. As well as if possible make YouTube video on how to start using this wonderful app. So many people like me have not coding and technical knowledge. It will be helpful for me as well as other.

**Comment by narenkram** [comment]
@krinacool I've started Shoonya integration. will be available in next few days.

**Comment by narenkram** [comment]
@krinacool @jenyjos Shoonya has been added.

**Comment by narenkram** [comment]
@jenyjos kill switch confirmation has been added
