### ISSUE TITLE
My suggestions

### ISSUE THREAD

**Issue by ParameshReddyD** [narenkram/steadfast-monorepo#10]
1. Pnl is not updating reguraly, there should a button for refresh or completly solve it to update on every second atleast.
2. The Notifications are coming miidle f the screen with big pop up and, its better put notification right top side of the page,

Just there are my suggestions only. 

overall app is very very good and working like a charm. you did a fantastic job.

Thanks
paramesh

**Comment by narenkram** [comment]
@ParameshReddyD Pnl updates every second already, is your LTP working? if not, you have not installed the app properly. DM me on Telegram with Anydesk code, i'll fix it.

**Comment by ParameshReddyD** [comment]
i have installed app correctly but only thing missing in my system is i have lower level of node versions.
![image](https://github.com/user-attachments/assets/7c858678-9798-4c59-b957-72f205fa5527)

**Comment by narenkram** [comment]
@ParameshReddyD If LTP is working, Pnl will automatically work.

**Comment by ParameshReddyD** [comment]
Yes, my LTP is not working someHow, idk how to Dm you on telegram? i have joined telegram channel

**Comment by narenkram** [comment]
@ParameshReddyD click this https://t.me/narenkram

**Comment by narenkram** [comment]
Notification was browser issue.

**Comment by ParameshReddyD** [comment]
Thanks @narenkram for your connecting through anyDesk and quick solution, I understand that this issue is because Anaconda is not letting me maintain proper packages in my pc, so i am planning to uninstall and use only python 3.12.

anyway this issue is now resolved.

Thanks alot
