### ISSUE TITLE
Cannot connect with broker, why?

### ISSUE THREAD

**Issue by reprasanna** [narenkram/steadfast-monorepo#11]
with reference to the above, user id and password, entered and did not get otp click. how to connect with otp.
tried paper trading also. this also not working

![image](https://github.com/user-attachments/assets/b89b109c-5d2e-4575-9bb6-11a38b19486e)

kindly explain

**Comment by narenkram** [comment]
@reprasanna  Use TOTP, first add your secret key to 2fa Google Authenticator.

**Comment by narenkram** [comment]
@reprasanna paper Trading has not implemented yet.

**Comment by reprasanna** [comment]
google authenticator done. request failed 400 error now

**Comment by narenkram** [comment]
DM me on telegram https://t.me/narenkram with your Anydesk or TeamViewer code.

**Comment by narenkram** [comment]
@reprasanna your broker details might be incorrect that's why your getting error 400
