### ISSUE TITLE
Fixed and manual Qty

### ISSUE THREAD

**Issue by krinacool** [narenkram/steadfast-monorepo#3]
Hello,

As of now it's only has 1 lot fixed. Is it possible to add manual quantity. Also please try to make slice of order like Zerodha Iceberg order so if qty is more than freezing limit it will help to close all orders.

Thanks & Regards

**Comment by narenkram** [comment]
More quantity added to some limited extent, For slice orders like Zerodha Iceberg, I don't  have huge funds to test and implement that feature for now.
