### ISSUE TITLE
everything goes fine

### ISSUE THREAD

**Issue by vettath** [narenkram/steadfast-monorepo#7]
everything goesfine but the index price is not updating I mean the ltp

**Comment by narenkram** [comment]
@vettath You did not install properly.
Watch https://youtu.be/O3-0XRyE5kI for assistance,
If you still face LTP problem, DM me on telegram (https://t.me/narenkram) with your Anydesk code, I'll help you setup the app.

**Comment by vettath** [comment]
Thank you for your great work and willingness to help. Now it is working
but I feel that there is a issue with refreshing new LTP while selecting
new index or strike rate may be this is the issue of my pc

**Comment by narenkram** [comment]
@vettath It takes upto a second to get the new LTPs when you change a index, if LTP did not load properly, just hit reload.

**Comment by vettath** [comment]
Yes it is working fine now. If you think it's possible to add equity (which
is updated from a watch list)also to the system it will be helpful full to
trade with your upcoming automation

**Comment by shivachikkalli** [comment]
While restarting make sure all the CMD windows opened during the last session are closed.

**Comment by vettath** [comment]
Hello,

This scalping system going to be the best I appreciate the effort you and
your team investing on this project

I have request for strategy while implementing please add range break out
with user editable time. Like for example the break out of 9:20 three min
candle
