### ISSUE TITLE
Reversal Protection / Profit Lock / Target Trailing - Request Feature

### ISSUE THREAD

**Issue by jenyjos** [narenkram/steadfast-monorepo#9]
Hi. could you please add one more feature to this app? ... Once the LTP move certain numbers, move SL to cost price or Cost Price + User given points. then Trail by Stop Loss trailing points. It can increase the chance to get profit insted of hitting SL without making any profit in case of reversal.
eg: Bought CE at LTP 100 Rupees. SL is 80, Target is 140. as per the current settings option we have a normal SL trail ... so when LTP moved to 115, SL will move to 95...when price revesed then LTP will hit SL at 95 and we loose 5 points as LOSS. 
insted you could add the feature I have requested as , if user gave 10 Points as LOCK  at BUY price and SL trail from there,  then when LTP become 110, SL will move to 100 insted of 90 as our normal SL trailing... when Price become 115 SL will be 105.... so when price start to reverse without hiting the target we could save at least 5 points.  if you could add a percentage wise increase towards the target on SL we can take most out of it. (means: if Profit LOCK SL start at 10..  then price gradually move towards the target SL gap comes narrow first 9, then 8, then 7 .. so on... So user can give a big Target without much risk..
I hope , you could understand what I tried to explain. For better understanding kindly go through this youtube link https://www.youtube.com/watch?v=h6jDjnupa6w&t=531s . I hope soon I could use this feature in your software. Thanks

**Comment by narenkram** [comment]
Such features are in plans, will add when I can.
